version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/bxt-ipc-types"
    schedule:
      interval: "daily
  - package-ecosystem: "cargo"
    directory: "/bxt-macros"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/bxt-patterns"
    schedule:
      interval: "daily
  - package-ecosystem: "cargo"
    directory: "/bxt-strafe"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/bxt-vct"
    schedule:
      interval: "daily"
